import {SUBJECTS} from '../data/subjects.js';
import {UNITS} from '../data/curriculum.js';
import {CONCEPTS} from '../data/concepts.js';
import {QUESTIONS} from '../data/questions.js';
import {SOURCES} from '../data/sources.js';
import {DATA_META} from '../data/meta.js';
import {store} from './store.js';
import {syncFromHash,navigate,conceptRoute} from './router.js';
import {make,$,$$,focusMain,downloadText,readFile,announce,formatDateTime,debounce} from './utils.js';
import {subjectProgress,overallProgress,progressBySubject,weakTopics} from './progress.js';
import {getDueReviews} from './scheduler.js';
import {getMastery,masteryLabel} from './mastery.js';
import {searchCurriculum} from './search.js';
import {renderLesson} from './lesson-player.js';
import {askMimi,mimiAvailability} from './mimi.js';
import {validateDataset} from './data-contracts.js';

const subjectById=Object.fromEntries(SUBJECTS.map(x=>[x.id,x]));
const unitById=Object.fromEntries(UNITS.map(x=>[x.id,x]));
const conceptById=Object.fromEntries(CONCEPTS.map(x=>[x.id,x]));
const unitsBySubject=UNITS.reduce((m,u)=>((m[u.subjectId]??=[]).push(u),m),{});
const conceptsByUnit=CONCEPTS.reduce((m,c)=>((m[c.unitId]??=[]).push(c),m),{});
const audit=validateDataset({subjects:SUBJECTS,units:UNITS,concepts:CONCEPTS,questions:QUESTIONS});
let deferredInstall=null,lastRouteKey='';

function navButton(label,route,icon=''){const b=make('button',{type:'button',class:'nav-link',dataset:{route},'aria-label':label});b.append(make('span',{class:'nav-icon',text:icon}),make('span',{text:label}));b.addEventListener('click',()=>navigate(route));return b;}
function buildShell(){
  document.body.replaceChildren();
  const skip=make('a',{class:'skip-link',href:'#main',text:'Skip to main content'});
  const top=make('header',{class:'topbar'});const menu=make('button',{type:'button',class:'icon-btn mobile-only','aria-label':'Open navigation',text:'☰'});menu.addEventListener('click',()=>{store.dispatch({type:'SET_UI',key:'sidebarOpen',value:!store.getState().ui.sidebarOpen});applyUI();});
  const brand=make('button',{type:'button',class:'brand','aria-label':'Ariana Study Hub home'});brand.append(make('span',{class:'brand-heart',text:'💜'}),make('span',{},[make('strong',{text:'Ariana Study Hub'}),make('small',{text:'Grade 8 • Jamaica'})]));brand.addEventListener('click',()=>navigate('home'));
  const topActions=make('div',{class:'top-actions'});const search=make('button',{type:'button',class:'icon-btn','aria-label':'Search',text:'⌕'});search.addEventListener('click',()=>navigate('search'));const settings=make('button',{type:'button',class:'icon-btn','aria-label':'Settings',text:'⚙'});settings.addEventListener('click',()=>navigate('settings'));topActions.append(search,settings);top.append(menu,brand,topActions);
  const layout=make('div',{class:'app-layout'});const side=make('aside',{id:'sidebar',class:'sidebar','aria-label':'Study navigation'});side.append(make('h2',{text:'Study Hub'}),navButton('Home','home','⌂'),navButton('Subjects','subjects','📚'),navButton('Review','review','↻'),navButton('Progress','progress','▥'),navButton('Search','search','⌕'));
  const sideProgress=make('div',{class:'sidebar-progress'});sideProgress.append(make('span',{text:'Overall mastery'}),make('div',{class:'progress-track'},make('i',{id:'sideProgressFill'})),make('small',{id:'sideProgressLabel',text:'0%'}));side.append(sideProgress);
  const main=make('main',{id:'main',tabIndex:-1});layout.append(side,main);
  const bottom=make('nav',{class:'bottom-nav','aria-label':'Mobile navigation'});bottom.append(navButton('Home','home','⌂'),navButton('Subjects','subjects','📚'),navButton('Review','review','↻'),navButton('Progress','progress','▥'));
  const mimiBtn=make('button',{type:'button',id:'mimiLauncher',class:'mimi-launcher','aria-label':'Open Mimi tutor','aria-expanded':'false'});mimiBtn.append(make('span',{text:'💜'}),make('span',{class:'mimi-launcher-label',text:'Ask Mimi'}));mimiBtn.addEventListener('click',()=>store.dispatch({type:'TOGGLE_MIMI'}));
  const mimi=make('section',{id:'mimiPanel',class:'mimi-panel','aria-label':'Mimi tutor','aria-hidden':'true'});
  const mh=make('header',{class:'mimi-head'},[make('div',{},[make('strong',{text:'💜 Mimi'}),make('small',{id:'mimiStatus',text:'Checking tutor mode…'})]),make('button',{type:'button',class:'icon-btn','aria-label':'Close Mimi',text:'×'})]);mh.lastElementChild.addEventListener('click',()=>store.dispatch({type:'TOGGLE_MIMI',open:false}));
  const context=make('div',{id:'mimiContext',class:'mimi-context',text:'Ask any Grade 8 question.'});const chat=make('div',{id:'mimiChat',class:'mimi-chat','aria-live':'polite'});chat.append(make('div',{class:'chat-bubble bot',text:'Hi Ariana! Ask me a question, show me what you tried, or ask for a hint. I’ll use the current lesson when possible.'}));
  const controls=make('div',{class:'mimi-controls'});const mode=make('select',{id:'mimiMode','aria-label':'Mimi help mode'});[['explain','Explain'],['hint','Hint only'],['check','Check my answer'],['quiz','Quiz me']].forEach(([v,t])=>mode.append(make('option',{value:v,text:t})));const input=make('textarea',{id:'mimiInput',rows:2,placeholder:'Type your question…','aria-label':'Question for Mimi'});const send=make('button',{type:'button',class:'btn primary',text:'Send'});send.addEventListener('click',sendMimi);input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMimi();}});controls.append(mode,input,send);mimi.append(mh,context,chat,controls);
  const live=make('div',{id:'liveRegion',class:'sr-only','aria-live':'polite','aria-atomic':'true'});const offline=make('div',{id:'offlineBanner',class:'offline-banner',hidden:true,text:'Offline: core lessons and saved progress are still available.'});
  document.body.append(skip,top,offline,layout,bottom,mimiBtn,mimi,live);applyPrefs();applyUI();updateGlobalProgress();mimiAvailability().then(x=>$('#mimiStatus').textContent=x.label);
}
function applyPrefs(){const p=store.getState().preferences;document.documentElement.classList.toggle('large-text',!!p.largeText);document.documentElement.classList.toggle('high-contrast',!!p.highContrast);document.documentElement.classList.toggle('reduce-motion',!!p.reducedMotion);document.documentElement.classList.toggle('dark-mode',!!p.darkMode);}
function applyUI(){const st=store.getState();$('#sidebar')?.classList.toggle('open',!!st.ui.sidebarOpen);const open=!!st.session.mimiOpen;$('#mimiPanel')?.classList.toggle('open',open);$('#mimiPanel')?.setAttribute('aria-hidden',String(!open));$('#mimiLauncher')?.setAttribute('aria-expanded',String(open));if(open){const c=conceptById[st.session.currentConcept];const u=c?unitById[c.unitId]:null;$('#mimiContext').textContent=c?`Current lesson: ${subjectById[c.subjectId]?.name} → ${u?.title} → ${c.title}`:'Ask any Grade 8 question.';setTimeout(()=>$('#mimiInput')?.focus(),50);}}
function updateGlobalProgress(){const p=overallProgress();if($('#sideProgressFill'))$('#sideProgressFill').style.width=p.percent+'%';if($('#sideProgressLabel'))$('#sideProgressLabel').textContent=`${p.percent}% • ${p.mastered}/${p.total} mastered`;}
function sectionHeading(kicker,title,desc=''){const h=make('header',{class:'page-head'});if(kicker)h.append(make('div',{class:'kicker',text:kicker}));h.append(make('h1',{text:title}));if(desc)h.append(make('p',{class:'lead',text:desc}));return h;}
function stat(label,value,detail=''){const a=make('article',{class:'stat-card'});a.append(make('strong',{text:String(value)}),make('span',{text:label}));if(detail)a.append(make('small',{text:detail}));return a;}
function subjectCard(s){const p=subjectProgress(s.id);const b=make('button',{type:'button',class:'subject-card','aria-label':`${s.name}, ${p.percent}% progress`});b.append(make('span',{class:'subject-icon',text:s.icon}),make('span',{class:'subject-title',text:s.name}),make('span',{class:'subject-summary',text:s.summary}),make('div',{class:'progress-track'},make('i',{style:`width:${p.percent}%`})),make('small',{text:`${p.percent}% • ${p.mastered}/${p.total} concepts mastered`}));b.addEventListener('click',()=>navigate('subject',s.id));return b;}
function routeKey(st){return [st.session.route,st.session.currentSubject,st.session.currentUnit,st.session.currentConcept].join('|');}
function renderHome(main){const st=store.getState(),p=overallProgress(st),due=getDueReviews(st),weak=weakTopics(st,3),recent=st.history.recent[0];main.append(sectionHeading('Welcome back',`Hi ${st.learner.name}!`,`Choose one useful next step. The Hub will use diagnostics and review history to avoid reteaching what you already know.`));
  const hero=make('section',{class:'hero-card'});const copy=make('div');copy.append(make('span',{class:'pill',text:'Today’s focus'}));if(due.length){const c=conceptById[due[0].conceptId];copy.append(make('h2',{text:'You have review work due'}),make('p',{text:`Start with ${c?.title||'a due concept'} so older learning stays strong.`}));}else if(recent){const c=conceptById[recent.conceptId];copy.append(make('h2',{text:`Continue ${c?.title||'your last lesson'}`}),make('p',{text:'Resume from the exact concept you studied most recently.'}));}else copy.append(make('h2',{text:'Start with a subject you are studying now'}),make('p',{text:'The first quick check will decide what foundation, if any, needs review.'}));
  const actions=make('div',{class:'actions'});if(due.length)actions.append(actionButton('↻ Start due review',()=>startConcept(due[0].conceptId,'practice'),'primary'));if(recent)actions.append(actionButton('▶ Resume learning',()=>startConcept(recent.conceptId),'primary'));actions.append(actionButton('📚 Choose a subject',()=>navigate('subjects')));hero.append(copy,actions);main.append(hero);
  const stats=make('section',{class:'stats-grid'});stats.append(stat('Overall learning',p.percent+'%'),stat('Concepts mastered',p.mastered,p.total+' total'),stat('Reviews due',p.due),stat('Practice attempts',st.history.attempts.length));main.append(stats);
  if(weak.length){const panel=make('section',{class:'panel'});panel.append(make('div',{class:'section-title'},[make('h2',{text:'Topics to strengthen'}),make('p',{text:'These come from actual answer history, not from a manual “mark done” button.'})]));const list=make('div',{class:'compact-list'});weak.forEach(x=>{const row=make('button',{type:'button',class:'compact-row'});row.append(make('span',{},[make('strong',{text:x.concept.title}),make('small',{text:`Accuracy ${Math.round((x.score||0)*100)}% • mastery ${x.level}/5`})]),make('span',{text:'Review →'}));row.addEventListener('click',()=>startConcept(x.concept.id,'learn'));list.append(row);});panel.append(list);main.append(panel);}
  const subjectPanel=make('section',{class:'panel'});subjectPanel.append(make('div',{class:'section-title'},[make('h2',{text:'Subjects'}),actionButton('View all',()=>navigate('subjects'),'subtle')]));const grid=make('div',{class:'subject-grid home-subjects'});SUBJECTS.slice(0,6).forEach(s=>grid.append(subjectCard(s)));subjectPanel.append(grid);main.append(subjectPanel);
}
function actionButton(text,fn,kind=''){const b=make('button',{type:'button',class:`btn ${kind}`,text});b.addEventListener('click',fn);return b;}
function renderSubjects(main){main.append(sectionHeading('Curriculum','Choose a subject','Search or browse all 18 subject areas. Progress reflects mastery levels, not page views.'));const search=make('input',{type:'search',class:'search-box',placeholder:'Search subjects or units…','aria-label':'Search subjects or units'});const grid=make('div',{class:'subject-grid'});SUBJECTS.forEach(s=>grid.append(subjectCard(s)));search.addEventListener('input',debounce(()=>{const q=search.value.toLowerCase().trim();[...grid.children].forEach((card,i)=>{const s=SUBJECTS[i],text=[s.name,s.summary,...(unitsBySubject[s.id]||[]).flatMap(u=>[u.title,u.focus])].join(' ').toLowerCase();card.hidden=q&&!text.includes(q);});},100));main.append(search,grid);}
function unitProgress(u){const cs=conceptsByUnit[u.id]||[];if(!cs.length)return 0;const sum=cs.reduce((a,c)=>a+Math.min(4,getMastery(c.id).level||0),0);return Math.round(sum/(cs.length*4)*100);}
function renderSubject(main,sid){const s=subjectById[sid];if(!s)return renderSubjects(main);main.append(sectionHeading(s.curriculumStatus==='official'?'Ministry-aligned curriculum':'School sequence to confirm',`${s.icon} ${s.name}`,s.summary));if(s.curriculumStatus==='confirm')main.append(notice('This subject area is included for study, but the exact Holy Childhood Grade 8 term sequence still needs the school outline/booklist before it can be labelled exact.','warning'));
  const groups={};for(const u of unitsBySubject[s.id]||[])(groups[u.term]??=[]).push(u);for(const [term,us] of Object.entries(groups)){const sec=make('section',{class:'panel'});sec.append(make('h2',{text:term}));const list=make('div',{class:'unit-list'});us.forEach(u=>{const pct=unitProgress(u),cs=conceptsByUnit[u.id]||[];const row=make('button',{type:'button',class:'unit-row'});row.append(make('span',{},[make('strong',{text:u.title}),make('small',{text:u.focus})]),make('span',{class:'unit-progress'},[make('span',{text:`${pct}%`}),make('small',{text:`${cs.length} concepts`})]));row.addEventListener('click',()=>navigate('unit',u.id));list.append(row);});sec.append(list);main.append(sec);}}
function notice(text,kind='info'){return make('div',{class:`notice ${kind}`,role:'note',text});}
function renderUnit(main,uid){const u=unitById[uid];if(!u){navigate('subjects');return;}const s=subjectById[u.subjectId],cs=conceptsByUnit[u.id]||[];main.append(sectionHeading(`${s.name} • ${u.term}`,u.title,u.focus));const intro=make('section',{class:'panel compact'});intro.append(make('div',{class:'section-title'},[make('h2',{text:'Learning path'}),make('span',{class:'pill',text:`${unitProgress(u)}% unit progress`})]),make('p',{text:'Start at the first concept you have not mastered. The diagnostic can skip foundations you already know.'}));main.append(intro);
  const list=make('ol',{class:'concept-path'});cs.forEach((c,i)=>{const m=getMastery(c.id);const li=make('li');const b=make('button',{type:'button',class:'concept-row'});const status=m.level>=4?'Mastered':m.level>=2?'In progress':'Not started';b.append(make('span',{class:'concept-number',text:String(i+1)}),make('span',{class:'concept-copy'},[make('strong',{text:c.title}),make('small',{text:c.prerequisites?.length?`Builds on ${c.prerequisites.map(x=>conceptById[x]?.title||x).join(', ')}`:'Foundation concept'})]),make('span',{class:`status-chip level-${m.level||0}`,text:`${status} • ${m.level||0}/5`}));b.addEventListener('click',()=>startConcept(c.id));li.append(b);list.append(li);});main.append(list);}
function startConcept(id,phase=null){const c=conceptById[id];if(!c)return;if(phase){store.dispatch({type:'SAVE_PROGRESS',conceptId:id,progress:{phase}});store.dispatch({type:'SET_LESSON_PHASE',phase});}conceptRoute(c);}
function renderReview(main){const due=getDueReviews(),st=store.getState();main.append(sectionHeading('Spaced review','Review what is due','Review dates are scheduled from performance so practice is spread over time instead of crammed into one sitting.'));if(!due.length){main.append(notice('Nothing is due right now. Continue learning and the Hub will schedule future reviews after mastery checks.','success'));const weak=weakTopics(st,8);if(weak.length){const p=make('section',{class:'panel'});p.append(make('h2',{text:'You can still strengthen these topics'}));const l=make('div',{class:'compact-list'});weak.forEach(x=>{const r=make('button',{type:'button',class:'compact-row'});r.append(make('span',{},[make('strong',{text:x.concept.title}),make('small',{text:`Mastery ${x.level}/5`})]),make('span',{text:'Practise →'}));r.addEventListener('click',()=>startConcept(x.concept.id,'practice'));l.append(r);});p.append(l);main.append(p);}return;}
  const list=make('div',{class:'review-grid'});due.forEach(r=>{const c=conceptById[r.conceptId],u=c?unitById[c.unitId]:null,s=c?subjectById[c.subjectId]:null;if(!c)return;const card=make('article',{class:'review-card'});card.append(make('span',{class:'pill',text:`${s?.name||''}`}),make('h2',{text:c.title}),make('p',{text:u?.title||''}),make('small',{text:`Due ${formatDateTime(r.nextReview)} • previous interval ${r.intervalDays||1} day(s)`}),actionButton('Start review',()=>startConcept(c.id,'practice'),'primary'));list.append(card);});main.append(list);}
function renderProgress(main){const st=store.getState(),p=overallProgress(st);main.append(sectionHeading('Learning record','My Progress','Mastery comes from answer history and review, not from simply opening a lesson.'));const stats=make('section',{class:'stats-grid'});stats.append(stat('Overall mastery',p.percent+'%'),stat('Mastered concepts',p.mastered),stat('Reviews due',p.due),stat('Attempts recorded',st.history.attempts.length));main.append(stats);const panel=make('section',{class:'panel'});panel.append(make('h2',{text:'Progress by subject'}));const rows=make('div',{class:'progress-rows'});progressBySubject(st).forEach(x=>{const row=make('button',{type:'button',class:'progress-row'});row.append(make('span',{text:`${x.subject.icon} ${x.subject.name}`}),make('div',{class:'progress-track'},make('i',{style:`width:${x.percent}%`})),make('strong',{text:`${x.percent}%`}));row.addEventListener('click',()=>navigate('subject',x.subject.id));rows.append(row);});panel.append(rows);main.append(panel);const weak=weakTopics(st,12);if(weak.length){const w=make('section',{class:'panel'});w.append(make('h2',{text:'Weak-topic review'}));const list=make('div',{class:'compact-list'});weak.forEach(x=>{const row=make('button',{type:'button',class:'compact-row'});row.append(make('span',{},[make('strong',{text:x.concept.title}),make('small',{text:`${subjectById[x.concept.subjectId]?.name} • ${Math.round((x.score||0)*100)}% accuracy`})]),make('span',{text:'Review →'}));row.addEventListener('click',()=>startConcept(x.concept.id,'learn'));list.append(row);});w.append(list);main.append(w);}}
function renderSearch(main){main.append(sectionHeading('Find anything','Search the Hub','Search concept names, unit titles, curriculum focus areas and lesson vocabulary.'));const input=make('input',{id:'globalSearch',type:'search',class:'search-box',placeholder:'Try “equations”, “inference”, “relief”, “respiration”…','aria-label':'Search study hub'});const results=make('div',{class:'search-results'});const render=()=>{results.replaceChildren();const q=input.value.trim();if(!q){results.append(notice('Type a topic above. Results will appear here.'));return;}const hits=searchCurriculum(q,{limit:40});if(!hits.length){results.append(notice('No close match. Try a shorter curriculum word or a subject name.','warning'));return;}hits.forEach(h=>{const b=make('button',{type:'button',class:'search-result'});b.append(make('strong',{text:h.title}),make('small',{text:h.subtitle}),make('span',{text:'Open →'}));b.addEventListener('click',()=>h.kind==='concept'?startConcept(h.id):navigate('unit',h.id));results.append(b);});};input.addEventListener('input',debounce(render,120));main.append(input,results);setTimeout(()=>input.focus(),20);}
function renderSettings(main){const st=store.getState();main.append(sectionHeading('Preferences','Settings','Adjust how the Hub looks and back up Ariana’s learning record.'));const p=make('section',{class:'panel settings-grid'});p.append(settingText('Learner name',st.learner.name,v=>{const next={...store.getState(),learner:{...store.getState().learner,name:v||'Ariana'}};store.dispatch({type:'IMPORT_STATE',value:next});}),toggleSetting('Larger text','largeText',st.preferences.largeText),toggleSetting('High contrast','highContrast',st.preferences.highContrast),toggleSetting('Reduce motion','reducedMotion',st.preferences.reducedMotion),toggleSetting('Dark mode','darkMode',st.preferences.darkMode));main.append(p);
  const data=make('section',{class:'panel'});data.append(make('h2',{text:'Progress backup'}),make('p',{text:'Export creates a JSON backup you can save. Import restores a previous backup on this browser.'}));const acts=make('div',{class:'actions'});acts.append(actionButton('Export progress',()=>downloadText('ariana-study-progress.json',store.export(),'application/json'),'primary'));const lab=make('label',{class:'btn file-button',text:'Import progress'});const fi=make('input',{type:'file',accept:'application/json',hidden:true});fi.addEventListener('change',async()=>{try{const obj=JSON.parse(await readFile(fi.files[0]));store.dispatch({type:'IMPORT_STATE',value:obj});announce('Progress imported.');renderRoute();}catch{announce('That progress file could not be imported.');}});lab.append(fi);acts.append(lab);data.append(acts);main.append(data);
  const pwa=make('section',{class:'panel'});pwa.append(make('h2',{text:'Install & offline'}),make('p',{text:location.protocol.startsWith('http')?'When hosted on GitHub Pages, the service worker caches the app’s local curriculum, code and icons after a successful load. External websites and videos still require internet.':'Direct file mode can open the page, but ES-module and service-worker behaviour varies by browser. Use the GitHub Pages version for the full install/offline experience.'}));const install=actionButton('Install app',async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;}else announce('Use your browser menu and choose Install app or Add to Home screen if available.');},'primary');pwa.append(install);main.append(pwa);
  const source=make('section',{class:'panel'});source.append(make('div',{class:'section-title'},[make('h2',{text:'Curriculum & technical sources'}),actionButton('Open curriculum map',()=>navigate('audit'),'subtle')]));const ul=make('ul',{class:'source-list'});SOURCES.slice(0,20).forEach(s=>{const li=make('li');const a=make('a',{href:s.url,target:'_blank',rel:'noopener',text:s.title});li.append(a,make('small',{text:s.note||''}));ul.append(li);});source.append(ul);main.append(source);
  const danger=make('section',{class:'panel danger-zone'});danger.append(make('h2',{text:'Reset'}),make('p',{text:'Reset removes saved mastery, reviews and attempts from this browser.'}),actionButton('Reset all progress',()=>{if(confirm('Reset all Ariana Study Hub progress on this browser?')){store.dispatch({type:'RESET_STATE'});navigate('home');}},'danger'));main.append(danger);}
function settingText(label,value,onChange){const wrap=make('label',{class:'setting'});wrap.append(make('span',{text:label}));const input=make('input',{type:'text',value});input.addEventListener('change',()=>onChange(input.value.trim()));wrap.append(input);return wrap;}
function toggleSetting(label,key,value){const wrap=make('label',{class:'setting toggle'});const input=make('input',{type:'checkbox',checked:!!value});const span=make('span',{text:label});input.addEventListener('change',()=>{store.dispatch({type:'SET_PREF',key,value:input.checked});applyPrefs();});wrap.append(span,input);return wrap;}
function renderAudit(main){const reviewCount=CONCEPTS.filter(c=>c.contentStatus==='needs-author-review').length,confirm=SUBJECTS.filter(s=>s.curriculumStatus==='confirm');main.append(sectionHeading('Transparency','Curriculum Map & Data Audit','This page deliberately shows what is verified, what is only mapped, and what still needs human review.'));const stats=make('section',{class:'stats-grid'});stats.append(stat('Schema',audit.ok?'PASS':'FAIL'),stat('Subjects',SUBJECTS.length),stat('Units',UNITS.length),stat('Concepts',CONCEPTS.length));main.append(stats);main.append(notice(`${reviewCount} concept records still carry “needs-author-review”. The adaptive engine can teach from the migrated material, but this status is intentionally not converted into “teacher verified”.`,reviewCount?'warning':'success'));if(confirm.length)main.append(notice(`Exact school sequence still to confirm: ${confirm.map(x=>x.name).join(', ')}.`, 'warning'));
  const map=make('section',{class:'panel'});map.append(make('h2',{text:'Complete curriculum map'}));SUBJECTS.forEach(s=>{const details=make('details',{class:'audit-subject'});details.append(make('summary',{text:`${s.icon} ${s.name} — ${(unitsBySubject[s.id]||[]).length} units` }));const ul=make('ul');for(const u of unitsBySubject[s.id]||[]){const li=make('li');li.append(make('strong',{text:`${u.term}: ${u.title}`}),make('span',{text:` — ${u.focus}`}),make('small',{text:` ${conceptsByUnit[u.id]?.length||0} concepts • ${u.curriculumStatus}`}));ul.append(li);}details.append(ul);map.append(details);});main.append(map);if(audit.errors.length){const e=make('section',{class:'panel error'});e.append(make('h2',{text:'Schema errors'}));audit.errors.forEach(x=>e.append(make('p',{text:x})));main.append(e);}}
function renderConcept(main,cid){renderLesson(main,cid);}
function renderRoute(){const main=$('#main');if(!main)return;const st=store.getState(),key=routeKey(st);main.replaceChildren();$$('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.route===st.session.route));try{switch(st.session.route){case'subjects':renderSubjects(main);break;case'subject':renderSubject(main,st.session.currentSubject);break;case'unit':renderUnit(main,st.session.currentUnit);break;case'concept':renderConcept(main,st.session.currentConcept);break;case'review':renderReview(main);break;case'progress':renderProgress(main);break;case'search':renderSearch(main);break;case'settings':renderSettings(main);break;case'audit':renderAudit(main);break;default:renderHome(main);}lastRouteKey=key;updateGlobalProgress();applyUI();focusMain();}catch(e){console.error('Route render failed',e);main.replaceChildren(sectionHeading('Something went wrong','The Hub is still running','A screen could not be rendered.'),notice(e.message||'Unknown rendering error','warning'),actionButton('Return home',()=>navigate('home'),'primary'));}}
async function sendMimi(){const input=$('#mimiInput'),chat=$('#mimiChat');const q=input?.value.trim();if(!q||!chat)return;const user=make('div',{class:'chat-bubble user',text:q});chat.append(user);input.value='';const wait=make('div',{class:'chat-bubble bot thinking',text:'Mimi is thinking…'});chat.append(wait);chat.scrollTop=chat.scrollHeight;const st=store.getState();try{const r=await askMimi(q,{mode:$('#mimiMode')?.value||'explain',subjectId:st.session.currentSubject,conceptId:st.session.currentConcept});wait.className='chat-bubble bot';wait.textContent=r.text;const tag=make('small',{class:'mimi-layer',text:r.layer==='chrome-language-model'?'Smart Mimi • on-device Chrome AI':'Local Mimi • curriculum + deterministic tools'});wait.append(tag);}catch(e){wait.className='chat-bubble bot error';wait.textContent='I could not complete that request. The local lessons are still available; try a shorter question or open the matching subject.';}chat.scrollTop=chat.scrollHeight;}
function onlineStatus(){const b=$('#offlineBanner');if(b)b.hidden=navigator.onLine;}
function initPWA(){window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;});if('serviceWorker'in navigator&&/^https?:$/.test(location.protocol))navigator.serviceWorker.register('./sw.js').catch(e=>console.warn('Service worker registration failed',e));}
function init(){buildShell();syncFromHash();renderRoute();onlineStatus();window.addEventListener('online',onlineStatus);window.addEventListener('offline',onlineStatus);initPWA();let lastMimi=store.getState().session.mimiOpen;store.subscribe((st,action)=>{applyPrefs();applyUI();updateGlobalProgress();const key=routeKey(st);if(key!==lastRouteKey||['IMPORT_STATE','RESET_STATE','CROSS_TAB_SYNC'].includes(action.type))renderRoute();if(st.session.mimiOpen!==lastMimi){lastMimi=st.session.mimiOpen;applyUI();}});window.addEventListener('error',e=>{console.error(e.error||e.message);announce('A feature had a problem. The Hub is still running.');});window.addEventListener('unhandledrejection',e=>{console.error(e.reason);announce('An optional feature could not finish. Core lessons are still available.');});}
init();
