import {tokens,normalizeText,unique,esc} from './utils.js';

const SUBJECT_FRAMEWORK={
  math:{label:'Understand → model → calculate → check',why:'Mathematics is about relationships and patterns. The goal is not only to get an answer, but to know why the steps keep the relationship true.'},
  english:{label:'Read → find evidence → explain → check',why:'Strong English answers connect a claim to evidence from the text and then explain what that evidence shows.'},
  science:{label:'Observe → explain → use evidence → conclude',why:'Science connects observations and measurements to an explanation that can be checked against evidence.'},
  social:{label:'Point → Explain → Jamaica/Caribbean example → Link',why:'Social Studies answers are strongest when a clear point is explained and connected to a real society or situation.'},
  geography:{label:'Locate/describe → process → effect → place example',why:'Geography explains where things are, what physical or human process is happening, and how that process affects people and places.'},
  history:{label:'Claim → evidence → context → significance',why:'History is not just remembering dates. It uses evidence to explain what changed, why it changed, and why it mattered.'},
  french:{label:'Meaning → pattern → model → say/write it',why:'Language learning works best when you know what a phrase means, notice its pattern, and then use that pattern in a new sentence.'},
  spanish:{label:'Meaning → pattern → model → say/write it',why:'Language learning works best when you know what a phrase means, notice its pattern, and then use that pattern in a new sentence.'},
  it:{label:'Input → process → output → safety/check',why:'Information Technology becomes easier when you follow what information enters a system, what happens to it, what comes out, and how to use the system safely.'},
  civics:{label:'Idea → responsibility → Jamaican example → effect',why:'Civics connects rights, responsibilities, values and institutions to how people live together in Jamaica.'},
  resource:{label:'Need/problem → plan → make/do → test → improve',why:'Resource & Technology turns needs and resources into practical decisions, products or services through planning, safe action and evaluation.'},
  religion:{label:'Describe accurately → understand meaning → compare respectfully → reflect',why:'Religious Education requires accurate, respectful understanding of beliefs and practices, including viewpoints that may differ from your own.'},
  pe:{label:'Purpose → safe technique → practise → improve',why:'Physical Education combines knowledge of health and movement with safe practice and reflection on technique.'},
  music:{label:'Hear/see → name the element → explain the effect → perform/create',why:'Music learning connects what you hear or see in notation to the musical choices that create the sound.'},
  drama:{label:'Character/scene need → voice/body choice → action → audience effect',why:'Drama uses purposeful choices in voice, movement, character and relationships to communicate meaning to an audience.'},
  visual:{label:'Observe → choose element/principle → create/analyse → explain effect',why:'Visual Arts connects what you see with deliberate choices about line, shape, colour, texture, space and composition.'},
  career:{label:'Know yourself → research → compare → decide next step',why:'Career planning is a process of matching interests, abilities and values with reliable information about real opportunities and requirements.'},
  hfle:{label:'Notice → think → choose safely → get support when needed',why:'HFLE focuses on life skills: recognising a situation, thinking about consequences, making a safe choice and knowing when to get help.'}
};

const GLOSSARY={
  math:{variable:'a letter or symbol that stands for a number that may change',term:'one part of an algebraic expression, separated by + or − signs',coefficient:'the number multiplying a variable',expression:'a mathematical phrase made from numbers, variables and operations, without an equals sign',equation:'a statement that two mathematical expressions have the same value',inequality:'a comparison showing that one value is greater than, less than, or possibly equal to another',ratio:'a comparison of two quantities by division',percentage:'a number out of 100',gradient:'how steep a straight line is; change in y divided by change in x',intercept:'the point where a graph crosses an axis',index:'a small raised number showing how many times a base is multiplied by itself',base:'the number being repeatedly multiplied in a power, or the place-value system being used',mean:'the total of the values divided by how many values there are',median:'the middle value after numbers are put in order',mode:'the value that appears most often',probability:'a measure of how likely an event is',parallel:'lines in the same plane that stay the same distance apart and never meet',perpendicular:'lines that meet at a right angle'},
  english:{literal:'the exact, directly stated meaning',inference:'a conclusion you make by combining clues in the text with sensible reasoning',evidence:'a word, phrase, detail or example from a text that supports an answer',context:'the words and situation around a word or idea that help explain its meaning',main:'the most important idea a paragraph or text is mainly about',rhetorical:'a question asked mainly for effect or to make the audience think, not because the writer expects an answer',persuasion:'language used to influence what an audience thinks, feels or does',point:'the position or idea a writer or speaker is communicating'},
  science:{variable:'a factor that can change in an investigation',independent:'the variable deliberately changed by the investigator',dependent:'the variable measured or observed to see the effect of the change',control:'a factor kept the same to make a comparison fair',evidence:'observations or measurements used to support a scientific explanation',force:'a push or a pull',friction:'a force that opposes motion between surfaces that touch',nutrient:'a substance in food that the body needs for energy, growth, repair or healthy functioning',enzyme:'a biological substance that speeds up a chemical reaction in living things',respiration:'the chemical process in cells that releases energy from food',mixture:'two or more substances together without being chemically joined',solution:'a mixture in which one substance is dissolved evenly in another'},
  geography:{geography:'the study of places, environments and the relationships between people and their surroundings',relief:'the shape and height of the land — for example flat, rolling, hilly or mountainous',settlement:'a place where people live, from a small village to a large city',slope:'how steep or gentle the surface of the land is',plain:'a broad area of relatively flat or gently rolling land',topography:'the detailed shape and surface features of an area of land',accessibility:'how easy or difficult it is to reach a place',scale:'the relationship between a distance on a map and the real distance on the ground',climate:'the usual pattern of weather in a place over a long period',hazard:'a natural or human event that can cause harm',vulnerability:'how likely people, buildings or systems are to be harmed by a hazard'},
  history:{history:'the study of people, events and change in the past using evidence',source:'something that gives information about the past',primary:'a source created during the time being studied or by someone directly involved',secondary:'a later interpretation that uses other sources to explain the past',evidence:'information from sources used to support a historical claim',cause:'a reason why an event or change happened',consequence:'a result or effect of an event or decision',chronology:'the order in which events happened',continuity:'something that stayed similar over time',significance:'why a person, event or development is important'},
  french:{bonjour:'hello or good day',salut:'an informal hello or goodbye',nom:'name',âge:'age',verbe:'a word that expresses an action or state',être:'the French verb meaning “to be”',avoir:'the French verb meaning “to have”',article:'a small word such as le, la, un or une used with a noun',adjectif:'a word that describes a noun'},
  spanish:{hola:'hello',nombre:'name',verbo:'a word that expresses an action or state',precio:'price',gusta:'a form used in the pattern “me gusta…” to say that something is pleasing to you / you like it',tienda:'shop or store',salud:'health',tiempo:'weather or time, depending on context'},
  it:{hardware:'the physical parts of a computer that can be touched',software:'programs and instructions used by a computer',input:'data or instructions sent into a computer system',process:'what a computer does with input data',output:'information produced by a computer after processing',algorithm:'a clear ordered set of steps for solving a problem',binary:'a base-2 number system that uses only 0 and 1',network:'two or more devices connected so they can communicate or share resources',protocol:'a set of agreed rules for communication between devices'},
  civics:{citizenship:'membership in a country together with rights, responsibilities and participation',right:'a freedom or protection a person is entitled to',responsibility:'a duty or action a person is expected to carry out',patriotism:'care, commitment and responsible pride toward one’s country',justice:'fair treatment according to rules, rights and evidence',stewardship:'taking responsible care of something entrusted to you'},
  resource:{resource:'something useful for meeting a need or completing a task, such as time, money, materials, skills or tools',input:'a resource put into a process',production:'the process of making a good or providing a service',safety:'actions that reduce the chance of injury, damage or loss',evaluate:'to judge how well something worked using clear criteria',consumer:'a person who buys or uses goods and services'},
  religion:{belief:'an idea or conviction that a person or religious tradition accepts as true or meaningful',practice:'an action people perform as part of religious or spiritual life',worship:'acts used to show devotion, reverence or connection with the sacred',symbol:'an object, image or action that represents a deeper meaning',value:'a principle that guides choices and behaviour',tradition:'a belief, practice or custom passed through a community over time'},
  pe:{fitness:'the ability of the body to meet everyday physical demands with energy and control',technique:'the correct and efficient way of performing a skill',warmup:'gentle activity that prepares the body for harder exercise',balance:'the ability to keep the body stable and controlled',coordination:'using body parts together smoothly and accurately',endurance:'the ability to continue an activity for a period of time'},
  music:{pitch:'how high or low a sound is',duration:'how long or short a sound lasts',dynamics:'how loud or soft music is',rhythm:'the pattern of long and short sounds and silences in time',melody:'a sequence of pitches heard as a musical line',notation:'symbols used to record musical sounds and instructions'},
  drama:{character:'the person or role represented in a drama',motivation:'the reason a character wants or does something',gesture:'a purposeful movement that communicates meaning',status:'the relative power or importance of characters in a scene',conflict:'a struggle or problem between characters, goals or forces',stage:'the performance space or the planned position/action within a performance'},
  visual:{line:'a mark that moves from one point to another and can suggest direction, shape or movement',shape:'a flat enclosed area with height and width',form:'a three-dimensional shape with height, width and depth',colour:'the visual quality created by light, including hue, value and intensity',texture:'how a surface looks or feels',balance:'the distribution of visual weight in an artwork',contrast:'a strong difference between visual elements that makes them stand out'},
  career:{interest:'an activity or topic that attracts your attention and enjoyment',ability:'something you are capable of doing or learning to do',value:'a principle or priority that matters when making choices',qualification:'a recognised achievement or requirement showing preparation for further study or work',career:'a long-term pattern of learning, work roles and development',goal:'a result you plan and work toward'},
  hfle:{boundary:'a limit that helps protect a person’s comfort, safety and rights',consent:'clear, voluntary agreement to something; it can be withdrawn and must be respected',empathy:'trying to understand another person’s feelings and point of view',coping:'healthy ways of handling stress, difficult feelings or problems',pressure:'influence from other people or situations that may affect a decision',support:'help from trusted people or services when a situation is difficult or unsafe'}
};
function subjectGlossary(s){return GLOSSARY[s]||{};}
function definitionFor(subjectId,title){const q=normalizeText(title),g=subjectGlossary(subjectId);for(const [key,def] of Object.entries(g)){if(q===key||q.includes(key)||key.includes(q))return def;}return null;}
function memoryFor(term,def){const t=normalizeText(term);if(t==='relief')return 'Think “land relief map”: highs and lows show how the land rises and falls.';if(t==='coefficient')return 'The coefficient is the number “co-operating” with the variable: in 5x, 5 works with x.';if(t==='inference')return 'Inference = clues + what you already know → a sensible conclusion.';if(t==='independent')return 'Independent = I change it.';if(t==='dependent')return 'Dependent = data I measure because it depends on the change.';if(t==='gradient')return 'Gradient tells how much the line rises or falls for each step across.';if(t==='ratio')return 'Ratio = compare parts in the same order.';if(t==='primary')return 'Primary source = first-hand or from the period itself.';return '';
}
function cleanVocabulary(c){return (c.vocabulary||[]).filter(v=>v?.term&&!/This means Ariana should work through/i.test(v.definition||''));}
function topicWords(c,u){const raw=(c.title+' '+(u?.focus||'')).split(/[•/&(),-]+/).map(x=>x.trim()).filter(Boolean);return unique(raw).slice(0,8);}
function vocabFor(c,u){const out=[];const push=(term,definition)=>{if(!term||!definition||out.some(x=>normalizeText(x.term)===normalizeText(term)))return;out.push({term,definition,memory:memoryFor(term,definition)});};
  for(const v of cleanVocabulary(c))push(v.term,v.definition);
  for(const word of topicWords(c,u)){const d=definitionFor(c.subjectId,word);if(d)push(word,d);}
  const whole=definitionFor(c.subjectId,c.title);if(whole)push(c.title,whole);
  for(const [term,def] of Object.entries(subjectGlossary(c.subjectId))){if(out.length>=6)break;const hay=normalizeText(c.title+' '+(u?.focus||''));if(hay.includes(term)||tokens(c.title).some(t=>term.includes(t)))push(term,def);}
  if(!out.length)push(c.title,`In ${c.subjectId==='math'?'Mathematics':'this subject'}, “${c.title}” is the specific idea or skill this lesson focuses on. We will define it through examples before using it independently.`);
  return out.slice(0,6);
}
function localExample(subjectId,title){const q=normalizeText(title);
  if(subjectId==='geography'&&/relief|settlement|topography|slope/.test(q))return 'Imagine comparing relatively flatter land around Spanish Town with the steep roads and slopes of the Blue Mountains. Building, travelling and moving goods are usually easier on gentler land than on steep terrain.';
  if(subjectId==='geography'&&/hurricane|flood|drought|hazard/.test(q))return 'Jamaican communities prepare for hurricanes and flooding by paying attention to warnings, drainage, shelter planning and the vulnerability of homes and roads.';
  if(subjectId==='math'&&/percent|discount|tax|interest|money|ratio/.test(q))return 'Use a Jamaican-dollar situation: compare prices at two shops, calculate a discount on a JMD purchase, or share a school-club budget in a given ratio.';
  if(subjectId==='math')return 'Use familiar numbers such as bus fares, school marks, distances between Jamaican towns, or quantities used at home to practise the same rule.';
  if(subjectId==='science'&&/nutrition|digest|food/.test(q))return 'Build examples from familiar foods such as rice and peas, callaloo, fruit, fish, eggs or ground provisions, then focus on the nutrient or body process being studied.';
  if(subjectId==='science')return 'A school investigation in Jamaica can use ordinary safe materials and local observations; the scientific method is the same whether the question is about plants, motion, weather or materials.';
  if(subjectId==='english')return 'Use a short passage about school, community life, a Jamaican news topic or a Caribbean story, then point to the exact words that support the answer.';
  if(subjectId==='social'||subjectId==='civics')return 'Connect the idea to a Jamaican community, parish, national institution, cultural practice or everyday responsibility rather than leaving the answer as a definition only.';
  if(subjectId==='history')return 'Use named Jamaican or Caribbean events, people and institutions when the source material supports them, and always separate evidence from opinion.';
  if(subjectId==='french'||subjectId==='spanish')return 'Imagine a real conversation at school, at a shop, with a visitor, or while travelling in the Caribbean. Use the target language to communicate one practical meaning at a time.';
  if(subjectId==='it')return 'Use a familiar device such as a school laptop, phone or desktop computer, and trace what the user inputs, what the system processes, and what output appears.';
  if(subjectId==='career')return 'Compare real Jamaican career pathways by looking at tasks, training requirements, working conditions and the skills a student would need to build.';
  if(subjectId==='hfle')return 'Use a realistic school, family or online situation and practise making a safe, respectful decision, including when to ask a trusted adult for help.';
  return 'Connect the idea to a familiar school, home or community situation so the meaning is concrete before moving to an abstract definition.';
}
function causeChain(c,u){const q=normalizeText(c.title+' '+(u?.title||''));
  if(c.subjectId==='geography'&&/relief.*settlement|settlement.*relief/.test(q))return['Land can be flat, gently rolling or steep.','Steeper land makes road and building construction more difficult and often more expensive.','Harder access can reduce the amount and size of development that is practical.','That helps explain why settlement patterns often differ between flatter plains and steep mountain areas.'];
  if(c.subjectId==='science'&&/independent.*dependent|variable/.test(q))return['The investigator changes one factor on purpose.','That changed factor is the independent variable.','Another factor is measured to see the result; that is the dependent variable.','Other important factors are kept the same so the comparison is fair.'];
  if(c.subjectId==='math'&&/equation/.test(q))return['An equation says the left side and right side have equal value.','Any operation done to one side must also be done to the other side to keep that equality true.','Use inverse operations to undo what is attached to the variable.','Check by substituting the answer back into the original equation.'];
  if(c.subjectId==='english'&&/infer|evidence/.test(q))return['The text gives a clue.','You connect that clue with what is reasonable in the situation.','You make a conclusion that is not stated word-for-word.','You support the conclusion by pointing back to the clue.'];
  const f=SUBJECT_FRAMEWORK[c.subjectId]||SUBJECT_FRAMEWORK.social;return[`First identify exactly what “${c.title}” means in this unit.`,`Next look at a clear example and notice the important feature.`,`Then use the subject method: ${f.label}.`,`Finally explain or check the result in your own words.`];
}
function explain(c,u){const direct=definitionFor(c.subjectId,c.title);const ex=(c.examples||[])[0]?.replace(/^Example:\s*/i,'');const legacy=c.legacyReference?.simpleExplanation||'';
  if(c.subjectId==='geography'&&/relief.*settlement|settlement.*relief/.test(normalizeText(c.title+' '+u?.title)))return 'Relief means the shape and height of the land. Settlement means a place where people live. Relief can affect settlement because steep or rugged land is usually harder and more expensive to build on and travel across, while flatter land often makes roads, buildings and services easier to develop. Relief is not the only factor — water, jobs, history, transport links and planning also matter — but it is one important physical factor.';
  if(c.subjectId==='math'&&normalizeText(c.title)==='equations')return 'An equation is a mathematical statement that says two expressions have equal value. Think of it like a balanced scale: if you change only one side, it is no longer balanced. To solve an equation, you use inverse operations to isolate the variable while doing the same thing to both sides. After finding the value, substitute it into the original equation to prove that both sides match.';
  if(c.subjectId==='english'&&/deduction|inference/.test(normalizeText(c.title)))return 'An inference is a conclusion that the writer does not state directly. You make it by combining evidence from the text with sensible background knowledge. A good inference is not a random guess: you should be able to point to a clue and explain how that clue supports your conclusion.';
  if(c.subjectId==='science'&&/independent.*dependent.*control|variable/.test(normalizeText(c.title)))return 'A variable is something that can change in an investigation. The independent variable is what the investigator changes on purpose, the dependent variable is what is measured or observed, and control variables are important conditions kept the same. Keeping the other conditions steady helps you decide whether the independent variable really caused the observed change.';
  if(direct)return `${c.title} means ${direct}. This lesson starts with that meaning, shows it in an example, and then helps you use the idea independently instead of only memorising the definition.`;
  if(ex)return `This concept is about ${c.title}. Start by studying one concrete example: ${ex} Then identify what changes, what stays the same, or what relationship the example demonstrates. The goal is to explain the rule in your own words and apply it to a new situation.`;
  if(legacy&&!/recognise a .* rule|syllabus focus/i.test(legacy))return legacy;
  return `${c.title} is one part of the unit “${u?.title||'this unit'}”. We will start with the basic meaning, connect it to an example, explain why it works, and then practise using it in a new question.`;
}
function workedExamples(c,u){const arr=[];for(const e of c.examples||[])if(e)arr.push(e.replace(/^Example:\s*/i,''));
  const q=normalizeText(c.title);
  if(c.subjectId==='math'&&q==='equations')arr.unshift('Solve 3x + 5 = 20: subtract 5 from both sides to get 3x = 15; divide both sides by 3 to get x = 5; check: 3(5)+5 = 20.');
  if(c.subjectId==='geography'&&/relief.*settlement/.test(q))arr.unshift('Compare two hypothetical sites: Site A is flat beside a main road; Site B is on a steep isolated slope. Site A is generally easier and cheaper for roads, buildings and services, so it may support denser development.');
  if(c.subjectId==='english'&&/infer/.test(q))arr.unshift('Text clue: “Keisha closed the window and pulled her sweater tighter.” Inference: the room or weather is probably cold. Evidence: she closes the window and adds warmth.');
  if(c.subjectId==='science'&&/variable/.test(q))arr.unshift('Question: Does more light affect plant growth? Change the amount of light (independent variable), measure plant growth (dependent variable), and keep plant type, soil, water and time the same (control variables).');
  while(arr.length<3){arr.push(`${localExample(c.subjectId,c.title)} Focus on the exact concept “${c.title}” and explain which part of the example shows it.`);}return arr.slice(0,3);
}
function misconceptions(c){const out=[];for(const m of c.commonMisconceptions||[]){if(typeof m==='string')out.push({mistake:m,correction:'Return to the definition and check each step against the example.'});else if(m?.mistake)out.push(m);}for(const m of c.legacyReference?.commonMistakes||[])out.push({mistake:m,correction:'Slow down, name the rule or idea first, and check the answer against the original question.'});
  const q=normalizeText(c.title);if(c.subjectId==='math'&&/equation/.test(q))out.unshift({mistake:'Changing only one side of an equation.',correction:'Whatever operation you perform on one side, perform the same operation on the other side.'});if(c.subjectId==='english'&&/infer/.test(q))out.unshift({mistake:'Giving a guess without evidence.',correction:'Name a clue from the text and explain how it supports the conclusion.'});if(c.subjectId==='science'&&/variable/.test(q))out.unshift({mistake:'Calling the measured result the independent variable.',correction:'Independent = deliberately changed; dependent = measured result.'});if(c.subjectId==='geography'&&/relief.*settlement/.test(q))out.unshift({mistake:'Saying relief alone determines where people live.',correction:'Relief is one factor. Jobs, water, transport, history, services and planning can also affect settlement.'});
  if(!out.length)out.push({mistake:'Repeating the definition without showing that you understand it.',correction:'Add a correct example and explain why the example fits the concept.'});return out.slice(0,4);
}
function visual(c,u){const q=normalizeText(c.title+' '+(u?.title||''));const p='#6c3cf0',g='#14866d',gold='#c99516',ink='#241b3c';
  if(c.subjectId==='geography'&&/relief|settlement|slope|topography/.test(q))return `<svg viewBox="0 0 760 320" role="img" aria-label="Comparison of flatter land and steep mountain land"><rect width="760" height="320" rx="22" fill="#fbfaff"/><text x="170" y="35" text-anchor="middle" font-size="22" font-weight="700" fill="${ink}">Gentler relief</text><path d="M30 230 C120 220 240 225 340 220" fill="none" stroke="${g}" stroke-width="10"/><path d="M55 195 L310 195" stroke="#555" stroke-width="12"/><rect x="90" y="145" width="55" height="45" fill="#f5c85b"/><rect x="180" y="135" width="65" height="55" fill="#b79cff"/><text x="170" y="275" text-anchor="middle" font-size="18" fill="${ink}">roads/buildings are easier to place</text><text x="570" y="35" text-anchor="middle" font-size="22" font-weight="700" fill="${ink}">Steep relief</text><path d="M400 245 Q490 45 570 135 Q635 210 730 245" fill="#e6defc" stroke="${p}" stroke-width="7"/><path d="M430 230 Q505 120 565 150" fill="none" stroke="#555" stroke-width="10"/><rect x="592" y="165" width="45" height="38" fill="#f5c85b" transform="rotate(-10 614 184)"/><text x="570" y="275" text-anchor="middle" font-size="18" fill="${ink}">roads/buildings need more effort</text><path d="M345 150 H395" stroke="${gold}" stroke-width="6"/><polygon points="395,150 380,140 380,160" fill="${gold}"/></svg>`;
  if(c.subjectId==='math'&&/equation|algebra/.test(q))return `<svg viewBox="0 0 760 300" role="img" aria-label="Balance model for an equation"><rect width="760" height="300" rx="22" fill="#fbfaff"/><line x1="380" y1="75" x2="380" y2="225" stroke="${ink}" stroke-width="8"/><polygon points="380,55 350,95 410,95" fill="${p}"/><line x1="170" y1="115" x2="590" y2="115" stroke="${ink}" stroke-width="8"/><line x1="200" y1="115" x2="145" y2="190" stroke="${ink}" stroke-width="4"/><line x1="560" y1="115" x2="615" y2="190" stroke="${ink}" stroke-width="4"/><rect x="75" y="190" width="140" height="18" rx="9" fill="${g}"/><rect x="545" y="190" width="140" height="18" rx="9" fill="${g}"/><text x="145" y="175" text-anchor="middle" font-size="30" font-weight="700" fill="${ink}">3x + 5</text><text x="615" y="175" text-anchor="middle" font-size="30" font-weight="700" fill="${ink}">20</text><text x="380" y="265" text-anchor="middle" font-size="20" fill="${ink}">Keep both sides balanced</text></svg>`;
  if(c.subjectId==='english'&&/infer|evidence|reading/.test(q))return `<svg viewBox="0 0 760 300" role="img" aria-label="Evidence plus reasoning leads to inference"><rect width="760" height="300" rx="22" fill="#fbfaff"/><rect x="55" y="90" width="190" height="100" rx="18" fill="#ece5ff" stroke="${p}" stroke-width="4"/><text x="150" y="132" text-anchor="middle" font-size="24" font-weight="700">TEXT CLUE</text><text x="150" y="165" text-anchor="middle" font-size="18">what the passage says</text><text x="300" y="150" font-size="38">+</text><rect x="345" y="90" width="175" height="100" rx="18" fill="#e5f6f1" stroke="${g}" stroke-width="4"/><text x="432" y="132" text-anchor="middle" font-size="24" font-weight="700">REASON</text><text x="432" y="165" text-anchor="middle" font-size="18">what the clue means</text><path d="M540 140 H610" stroke="${gold}" stroke-width="7"/><polygon points="625,140 605,127 605,153" fill="${gold}"/><rect x="620" y="90" width="110" height="100" rx="18" fill="#fff2c9" stroke="${gold}" stroke-width="4"/><text x="675" y="132" text-anchor="middle" font-size="22" font-weight="700">INFER</text><text x="675" y="165" text-anchor="middle" font-size="17">conclusion</text></svg>`;
  if(c.subjectId==='science'&&/variable|experiment|investig/.test(q))return `<svg viewBox="0 0 760 300" role="img" aria-label="Independent variable affects dependent variable while controls stay the same"><rect width="760" height="300" rx="22" fill="#fbfaff"/><rect x="45" y="85" width="200" height="105" rx="18" fill="#ece5ff" stroke="${p}" stroke-width="4"/><text x="145" y="125" text-anchor="middle" font-size="22" font-weight="700">CHANGE</text><text x="145" y="158" text-anchor="middle" font-size="18">independent variable</text><path d="M255 138 H345" stroke="${gold}" stroke-width="7"/><polygon points="360,138 340,125 340,151" fill="${gold}"/><rect x="370" y="85" width="200" height="105" rx="18" fill="#e5f6f1" stroke="${g}" stroke-width="4"/><text x="470" y="125" text-anchor="middle" font-size="22" font-weight="700">MEASURE</text><text x="470" y="158" text-anchor="middle" font-size="18">dependent variable</text><rect x="590" y="85" width="125" height="105" rx="18" fill="#fff2c9" stroke="${gold}" stroke-width="4"/><text x="652" y="120" text-anchor="middle" font-size="19" font-weight="700">KEEP SAME</text><text x="652" y="150" text-anchor="middle" font-size="16">controls</text><text x="380" y="245" text-anchor="middle" font-size="20">One fair comparison → better evidence</text></svg>`;
  const label=esc(c.title);return `<svg viewBox="0 0 760 280" role="img" aria-label="Learning model for ${label}"><rect width="760" height="280" rx="22" fill="#fbfaff"/><circle cx="125" cy="140" r="65" fill="#ece5ff" stroke="${p}" stroke-width="5"/><text x="125" y="136" text-anchor="middle" font-size="20" font-weight="700">MEANING</text><text x="125" y="162" text-anchor="middle" font-size="15">start here</text><path d="M200 140 H315" stroke="${gold}" stroke-width="7"/><polygon points="330,140 310,127 310,153" fill="${gold}"/><circle cx="415" cy="140" r="65" fill="#e5f6f1" stroke="${g}" stroke-width="5"/><text x="415" y="136" text-anchor="middle" font-size="20" font-weight="700">EXAMPLE</text><text x="415" y="162" text-anchor="middle" font-size="15">see it work</text><path d="M490 140 H595" stroke="${gold}" stroke-width="7"/><polygon points="610,140 590,127 590,153" fill="${gold}"/><circle cx="655" cy="140" r="65" fill="#fff2c9" stroke="${gold}" stroke-width="5"/><text x="655" y="136" text-anchor="middle" font-size="20" font-weight="700">USE IT</text><text x="655" y="162" text-anchor="middle" font-size="15">your turn</text></svg>`;
}
export function buildLessonContent(c,u,s){const vocabulary=vocabFor(c,u);const framework=SUBJECT_FRAMEWORK[c.subjectId]||SUBJECT_FRAMEWORK.social;return{
  intro:`Today we are learning “${c.title}”. First we will make sure the words are clear, then see the idea in action, practise it with help, and finally try it independently.`,
  summary:definitionFor(c.subjectId,c.title)||c.summary||`A focused Grade 8 concept within ${u?.title||s?.name||'this subject'}.`,
  explanation:explain(c,u),vocabulary,framework,chain:causeChain(c,u),worked:workedExamples(c,u),mistakes:misconceptions(c),jamaica:localExample(c.subjectId,c.title),visual:visual(c,u),
  sourceStatus:c.contentStatus||'needs-author-review',diagramIsOffline:true
};}
